a = input('Digite algo: ')
print('tipo primitivo e ', type(a))
print('E alfabetico?', a.isalpha())
print('Só tem numeros? ', a.isalnum())
print('E um numero? ', a.isnumeric())
print('Esta em maiusculo? ', a.isupper())
print('Esta em minuscolo? ', a.islower())
print('E alfanumerico? ',a.isalnum())
